#!/bin/sh
#Remove All BIN+OBJ Folders to force remove any old binary object references
find . -iname "bin" -type d | xargs rm -rf
find . -iname "obj" -type d | xargs rm -rf
find . -iname "Logs" -type d | xargs rm -rf

#SETUP BASE VARIABLES
PROJ_EXT="csproj"
BASE_DIR="/home/faisal/LocalFMASolutionsDev"
NUGET_OUTPUT=$BASE_DIR/NugetFactory
BASE_CODE_DIR=$BASE_DIR/GitHubRepos/FMASolutionsCore
PUBLISHED_SITES_BASE_DIR=$BASE_DIR/PublishedSites

#Delete Nuget Output to.
rm -rf $NUGET_OUTPUT  
mkdir $NUGET_OUTPUT/ 
rm -rf $PUBLISHED_SITES_BASE_DIR
mkdir $PUBLISHED_SITES_BASE_DIR/

#Build and Pack ClassLibs - Starting with our Data Services
#Build DataServices
CURRENT_WORKING_DIR=$BASE_CODE_DIR/DataServices

PROJECT_NAME=CryptoHelper
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=DataRepository
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=FileHelper
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=ShoppingRepo
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=WebHelper
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

#Build BusinessServices
CURRENT_WORKING_DIR=$BASE_CODE_DIR/BusinessServices

PROJECT_NAME=AppConfigExtension
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=AppLoggerExtension
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=BusinessCore
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=ControllerTemplate
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/


PROJECT_NAME=PoEProfitHunter
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=ShoppingService
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=SQLAppConfigTypes
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

#Build CommandLineTools
CURRENT_WORKING_DIR=$BASE_CODE_DIR/CLITools

PROJECT_NAME=CLIHelper
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=CryptoTester
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

PROJECT_NAME=ShoppingTester
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet pack $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $NUGET_OUTPUT/

#Build and publish Web sites/Apis
CURRENT_WORKING_DIR=$BASE_CODE_DIR/Web
PROJECT_NAME=FMASolutionsWebsite
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet publish $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $PUBLISHED_SITES_BASE_DIR/$PROJECT_NAME/

PROJECT_NAME=ShopBro
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet publish $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $PUBLISHED_SITES_BASE_DIR/$PROJECT_NAME/

PROJECT_NAME=API
/usr/bin/dotnet build $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT
/usr/bin/dotnet publish $CURRENT_WORKING_DIR/$PROJECT_NAME/$PROJECT_NAME.$PROJ_EXT -o $PUBLISHED_SITES_BASE_DIR/$PROJECT_NAME/